In [2]:
import numpy as np
x=np.zeros((3,5,2), dtype=np.float32)
print (x)
print (x.size)
print (x.shape)

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
30
(3, 5, 2)


In [20]:
y=np.array([[[5,0],[0,1]],
           [[0,1],[1,1]],[[0,1],[1,1]]])
print (y)
print (y.size)
print (y.shape)
print (y.shape[0])

[[[5 0]
  [0 1]]

 [[0 1]
  [1 1]]

 [[0 1]
  [1 1]]]
12
(3, 2, 2)
3


In [13]:
print (y[0,0,1])#Array[shape,row,column]

0


In [21]:
print (np.random.permutation(y.shape[0]))
print (np.random.permutation(y.shape[1]))
print (np.random.permutation(y.shape[2]))

[1 0 2]
[1 0]
[1 0]


In [25]:
print(np.unique(y[0]))
print(y)

[0 1 5]
[[[5 0]
  [0 1]]

 [[0 1]
  [1 1]]

 [[0 1]
  [1 1]]]


In [32]:
new_array = [tuple(row) for row in y[0]]
uniques = np.unique(new_array)
print (uniques)

[0 1 5]


In [34]:
data = np.array([[1,8,3,3,4],
                 [1,8,9,9,4],
                 [1,8,3,3,4]])
def unique_rows(a):
    a = np.ascontiguousarray(a)
    unique_a = np.unique(a.view([('', a.dtype)]*a.shape[1]))
    return unique_a.view(a.dtype).reshape((unique_a.shape[0], a.shape[1]))
print(unique_rows(data))

[[1 8 3 3 4]
 [1 8 9 9 4]]
